### PR TITLE
Update Utils.cs

### PR DESCRIPTION
**Pull request by SteAmeR**
This pull request is related to the issue https://github.com/EricZimmerman/ExtensionBlocks/issues/7

### CODE REVIEW

**Comment by SteAmeR** [comment]
I'm wondering, when will it be published as a NuGet package?

**Comment by EricZimmerman** [comment]
i mentioned asap in the issues thread. doing this now.

**Comment by EricZimmerman** [comment]
1.3.2 pushed.

**Comment by SteAmeR** [comment]
opss. LNK nuget update
nugetissue

**Comment by EricZimmerman** [comment]
on the way

**Pull request merged**
