### PR TITLE
Update Beef0004.cs

### PR DESCRIPTION
**Pull request by SteAmeR**
Please accept this push request because Line 75 doesn't perform a correct null string check and hence throws a critical exception. thnx

### CODE REVIEW

**Comment by EricZimmerman** [comment]
do you have an example of code where there ISNT a string at [0]? 

what is wrong with a string being null if its null? is my code throwing an extension, or code that is consuming it that is failing to do a null check?

**Comment by SteAmeR** [comment]
> do you have an example of code where there ISNT a string at [0]?
> 
> what is wrong with a string being null if its null? is my code throwing an extension, or code that is consuming it that is failing to do a null check?

The sample file causing this issue is an include malicious shortcut that malware sample. I'm attaching the sample here and image.
Capture
[29d211c29ea44814d873966c992c624c7d2a41f61d45cb20e075b84c902fabd4.zip](https://github.com/EricZimmerman/ExtensionBlocks/files/8782516/29d211c29ea44814d873966c992c624c7d2a41f61d45cb20e075b84c902fabd4.zip)

Zip file password is "infected"

**Comment by EricZimmerman** [comment]
working on this now. will have all nuget packages updated and LECmd updated here soon

**Comment by SteAmeR** [comment]
Thanks for your cooperation. And so is it possible to update your LNK repository for this fixed?

**Comment by EricZimmerman** [comment]
Yes. Of course. That's dependenh on this project so that nugget will be
updated, and finally lecmd, which depends on lnk

**Comment by EricZimmerman** [comment]
note that i manually edited the hex for the lnk file to make sure it cant detonate, which is why some of the commands look strange below:.

pushing LECmd update in 2. rest of nuget is live

image

**Pull request merged**
